language: python
python:
    - "2.7"
    
install:
  - pip install -r requirements.txt
   
before_install:
    - pip install pytest pytest-cov
    - pip install coverage
    - pip install coveralls
    
script:
    - pytest v1/test_app.py
    
after_success:
- coveralls
