language: python
python:
    - "3.6"
    

virtualenv:
    system_site_package: true

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

script:
- pytest v1/test_app.py
- coverage report
    
after_script:
- codeclimate-test-reporter
- coveralls

after_success:
    - coveralls

