language: python

#TEST COVERAGE ID to be used in all the test coverage reports
env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

python:
    - "3.6"
    

virtualenv:
    system_site_package: true

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls

#create the database
before_script:
  - psql -c 'create database book_a_meal_test_db;' -U postgres

script:
- coverage run --source='v1/' manage.py test 
- coverage report
    
after_script:
- codeclimate-test-reporter
- coveralls

after_success:
    - coveralls

