language: python
python:
    - "3.6"
    

virtualenv:
    system_site_package: true

install:
  - pip install -r requirements.txt

script:
- coverage run --source=run_tests.py test 
- coverage report

after_script:
#- codeclimate-test-reporter
- coveralls
    
after_success:
    - coveralls

