language: python
python:
    - "3.6"
    

virtualenv:
    system_site_package: true

install:
  - pip install -r requirements.txt

script:
- pytest v1/test_app.py
    
after_success:
    - coveralls

