language: python
python:
    - "3.6"
    

virtualenv:
    system_site_package: true

install:
  - pip install -r requirements.txt

script:
- coverage run --source='v1/' test_app.py test
    
after_success:
    - coveralls

