"""empty message

Revision ID: 447081da9629
Revises: ca2d7673c55c
Create Date: 2018-05-12 07:30:53.129963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447081da9629'
down_revision = 'ca2d7673c55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_meals',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.PrimaryKeyConstraint('menu_id', 'meal_id')
    )
    op.create_table('order_meals',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id', 'meal_id')
    )
    op.create_unique_constraint(None, 'menus', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_table('order_meals')
    op.drop_table('menu_meals')
    # ### end Alembic commands ###
