"""empty message

Revision ID: 5aafd22ad8ca
Revises: e3b4778deab7
Create Date: 2018-08-09 08:27:30.001254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aafd22ad8ca'
down_revision = 'e3b4778deab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_meals_meal_id_fkey', 'menu_meals', type_='foreignkey')
    op.create_foreign_key(None, 'menu_meals', 'meals', ['meal_id'], ['meal_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_meals', type_='foreignkey')
    op.create_foreign_key('menu_meals_meal_id_fkey', 'menu_meals', 'meals', ['meal_id'], ['meal_id'])
    # ### end Alembic commands ###
