"""empty message

Revision ID: 5ff3198675ee
Revises: 5aafd22ad8ca
Create Date: 2018-08-11 13:03:52.589353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff3198675ee'
down_revision = '5aafd22ad8ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('expiration', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'expiration')
    # ### end Alembic commands ###
