"""empty message

Revision ID: ca2d7673c55c
Revises: e643fb5d97a3
Create Date: 2018-05-11 21:22:08.702329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2d7673c55c'
down_revision = 'e643fb5d97a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'meals', 'users', ['vendor_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'vendor_id')
    # ### end Alembic commands ###
