"""empty message

Revision ID: e3b4778deab7
Revises: 84b8bc52f6fb
Create Date: 2018-08-09 08:23:38.361674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b4778deab7'
down_revision = '84b8bc52f6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_menu_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_meal_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'menus', ['menu_id'], ['menu_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'meals', ['meal_id'], ['meal_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_meal_id_fkey', 'orders', 'meals', ['meal_id'], ['meal_id'])
    op.create_foreign_key('orders_menu_id_fkey', 'orders', 'menus', ['menu_id'], ['menu_id'])
    # ### end Alembic commands ###
