"""empty message

Revision ID: e3fa22427e11
Revises: 5ff3198675ee
Create Date: 2018-08-28 18:41:44.875488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fa22427e11'
down_revision = '5ff3198675ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expiry', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.meal_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.email'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
