"""empty message

Revision ID: ef7d84267eb7
Revises: 91b388a5f06e
Create Date: 2018-05-12 08:49:53.008798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7d84267eb7'
down_revision = '91b388a5f06e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_date_key', 'orders', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('orders_date_key', 'orders', ['date'])
    # ### end Alembic commands ###
